In [1]:
import numpy as np

In [2]:
np.version.version

'1.24.2'

In [5]:
l = [1, 2, 3]
x = np.array(l, dtype='f') 
print( x.dtype )
l, x

float32


([1, 2, 3], array([1., 2., 3.], dtype=float32))

In [7]:
x = np.array([1, 2, 3], dtype='i2') # 'i2' == np.int16 
print( x.dtype )
x

int16


array([1, 2, 3], dtype=int16)

In [12]:
a=np.array([1,2,3])
print( a.dtype ) # 마지막 실행문이 아닌 경우 출력하려면 print 사용
a # 마지막 실행문은 자동 출력

int32


array([1, 2, 3])

In [13]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [16]:
a=np.array([1, 2, 3, 4, 5], ndmin=2)
a

array([[1, 2, 3, 4, 5]])

In [17]:
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)

(2, 3)


In [18]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
a.shape = (3,2) 
print (a) 

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
# b = a.reshape(3, 2) 
b = a.reshape(-1, 2) # 열은 2개, 행은 데이터에 따라서 자동 결정
print (b) 

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [21]:
a = np.arange(24) # range(24)와 동일한 기능을 제공하는 np의 함수
print(a.ndim) # 1
b = a.reshape(2,4,3) # 
print(b.ndim) # 3
print(b)

1
3
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [23]:
x2 = np.empty([3,2], dtype=int)
print(x2)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
x = np.zeros((5,), dtype="int")
print(x)

[0 0 0 0 0]


In [25]:
x = np.ones([2,2], dtype=int)
print(x)

[[1 1]
 [1 1]]


In [27]:
x = [1,2,3] 
a = np.asarray(x) 
a

array([1, 2, 3])

In [29]:
x = [(1,2,3),(4, 5, 6)] 
a = np.asarray(x) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
x = np.arange(10,20,2) 
x

array([10, 12, 14, 16, 18])

In [32]:
a = np.linspace(1.0, 2.0, num = 5) 
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [33]:
x = np.linspace(10, 20, 5, endpoint = False) 
print (x)
x = np.linspace(10, 20, 5, endpoint = True) 
print (x)

[10. 12. 14. 16. 18.]
[10.  12.5 15.  17.5 20. ]


In [34]:
x = np.linspace(1,2,5, retstep = True) 
print (x) 

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [68]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] # list
b = np.array(a) # numpy array

print( a[3], b[3] )
# print( a[[1, 5]]) # 한 번에 a[1], a[5]를 indexing -> list는 오류
print( b[[3, 1, 5]]) # 한 번에 a[1], a[5]를 indexing -> np.array 성공

3 3
[3 1 5]


In [49]:
a = np.arange(10) 
s = slice(2,7,1) # 2, 4, 6
print( a[s] ) # a[[2, 4, 6]]
print( a[[2, 4, 6]] )
print( [a[2], a[4], a[6]])
print( a[[2, 1, 7]])

[2 3 4 5 6]
[2 4 6]
[2, 4, 6]
[2 1 7]


In [50]:
a = np.arange(10) 
b = a[2:7:2] 
print (b)

[2 4 6]


In [51]:
a = np.arange(10) 
b = a[5] 
print (b)

5


In [52]:
a = np.arange(10) 
print (a[2:])

[2 3 4 5 6 7 8 9]


In [53]:
a = np.arange(10) 
print (a[2:5])

[2 3 4]


In [56]:
b = [[1,2,3],[3,4,5],[4,5,6]]
print(b[1:])

a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print (a) 
print (a[1:])


[[3, 4, 5], [4, 5, 6]]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]


In [61]:
l = [[1, 2], [3, 4], [5, 6]]
print(l[2][1])
x = np.array([[1, 2], [3, 4], [5, 6]]) 
print(x[2][1])
print(x[2, 1])

6
6
6


In [63]:
l = [[1, 2], [3, 4], [5, 6]]
# print( l[[0,1,2], [0,1,0]] ) 오류

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] # --> np.array([x[0, 0], x[1, 1], x[2, 0]])
print (y)

[1 4 5]


In [70]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]]) 
x.shape, x

((4, 3),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]))

In [71]:
z = x[1:4,1:3] # x[1,1], x[2,1], x[3, 1], x[1, 2], x[2, 2], x[3, 2]
z

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [72]:
y = x[1:4,[1,2]] 
y

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [73]:
x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
# x + 5
boolean_indexer = (x % 2 == 0)
# boolean_indexer = x > 5
boolean_indexer

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [79]:
x[boolean_indexer]

array([ 0,  2,  4,  6,  8, 10])

In [80]:
a = np.array([np.nan, 1,2,np.nan,3,4,5])
a

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [86]:
# a == np.nan # nan은 동일성 판단은 연산자로 수행할 수 없음
boolean_indexer = ~np.isnan(a) # nan 비교는 isnan 함수 사용, ~True -> False, ~False -> True

In [87]:
print(a[boolean_indexer])

[1. 2. 3. 4. 5.]


In [88]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]


In [89]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0]) 
print (a + b) # 연산할 때 b는 재사용

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [91]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
b = a.T 

print(a)
print(b)

for x in np.nditer(b): 
    print (x, end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 5 10 15 20 25 30 35 40 45 50 55 